replicaCount: 1

image:
  repository: ghcr.io/arriven/db1000n
  pullPolicy: Always
  # Available images: https://github.com/zlaya-sobaka/db1000n_mobile/pkgs/container/db1000n
  tag: latest

envVars:
- name: "ENABLE_PRIMITIVE"
  value: "false"

resources:
  {}
  # limits:
  #   cpu: 2
  #   memory: 2Gi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
