# this scenario copies the one from https://git.gay/a/ddos-guard-bypass/src/branch/master/index.js
# it is here for educational purposes only and is meant to showcase the capabilities of the tool
jobs:
  - type: sequence
    args:
      jobs:
        - type: set-value
          name: useragent
          args:
            value: "{{ random_user_agent }}"
        - type: log
          args:
            text: 'user-agent: {{ .Value (ctx_key "data.useragent") }}'
        - type: http-request
          name: initial
          args:
            request:
              method: GET
              path: https://noxx.is
              headers:
                User-Agent: '{{ .Value (ctx_key "data.useragent") }}'
                Accept: "text/html"
                Accept-Language: "en-US"
                Connection: "keep-alive"
                Sec-Fetch-Dest: "document"
                Sec-Fetch-Mode: "navigate"
                Sec-Fetch-Site: "none"
                Sec-Fetch-User: "?1"
                TE: "trailers"
                DNT: "1"
        - type: log
          args:
            text: 'cookies: {{ cookie_string (index (.Value (ctx_key "data.initial")) "response" "cookies") }}'
        - type: http-request
          name: check
          args:
            request:
              method: GET
              path: "https://check.ddos-guard.net/check.js"
              headers:
                User-Agent: '{{ .Value (ctx_key "data.useragent") }}'
                Accept: "*/*"
                Accept-Language: "en-US,en;q=0.5"
                Accept-Encoding: "gzip, deflate"
                Referer: https://noxx.is
                Cookie: '{{ cookie_string (index (.Value (ctx_key "data.initial")) "response" "cookies") }}'
                Sec-Fetch-Dest: "script"
                Sec-Fetch-Mode: "no-cors"
                Sec-Fetch-Site: "cross-site"
        - type: set-value
          name: check-body
          args:
            value: '{{ index (.Value (ctx_key "data.check")) "response" "body"}}'
        - type: set-value
          name: id
          args:
            value: '{{ index (split (index (split (.Value (ctx_key "data.check-body")) "/.well-known/ddos-guard/id/") 1) "''") 0 }}'
        - type: log
          args:
            text: 'id: {{ .Value (ctx_key "data.id") }}'
        - type: http-request
          name: final-cookies-request
          args:
            request:
              method: GET
              path: 'https://ddos-guard.net/.well-known/ddos-guard/id/{{ .Value (ctx_key "data.id") }}'
              headers:
                User-Agent: '{{ .Value (ctx_key "data.useragent") }}'
                Accept: "image/webp,*/*"
                Accept-Language: "en-US,en;q=0.5"
                Accept-Encoding: "gzip, deflate"
                Cache-Control: "no-cache"
                Referer: https://noxx.is
                Cookie: '{{ cookie_string (index (.Value (ctx_key "data.initial")) "response" "cookies") }}'
                Sec-Fetch-Dest: "script"
                Sec-Fetch-Mode: "no-cors"
                Sec-Fetch-Site: "cross-site"
        - type: set-value
          name: final-cookies
          args:
            value: '{{ cookie_string (index (.Value (ctx_key "data.final-cookies-request")) "response" "cookies") }}'
        - type: log
          args:
            text: 'cookies: {{ .Value (ctx_key "data.final-cookies") }}'
        - type: http-request
          name: actual-request
          args:
            request:
              method: GET
              path: https://noxx.is
              headers:
                User-Agent: '{{ .Value (ctx_key "data.useragent") }}'
                Referer: https://noxx.is
                Cookie: '{{ .Value (ctx_key "data.final-cookies") }}'
        - type: log
          args:
            text: 'body: {{ index (.Value (ctx_key "data.actual-request")) "response" "body" }}'
        - type: log
          args:
            text: 'headers: {{ index (.Value (ctx_key "data.actual-request")) "response" "headers" }}'
        - type: log
          args:
            text: 'cookies: {{ index (.Value (ctx_key "data.actual-request")) "response" "cookies" }}'
